sudo: false

language: ruby

cache:
  bundler: true

rvm:
  - 1.9.3
  - 2.3.0
  - ruby-head

script: bundle exec rspec --color

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
    - rvm: rbx-2
    - rvm: ree
